import './globals.css';
import {Plus_Jakarta_Sans} from 'next/font/google';
import ClientSkeletonProvider from '@/providers/ClientSkeletonProvider';

const plusJakartaSans = Plus_Jakarta_Sans({
    subsets:  ['latin'],
    variable: '--font-a',
    style:    'normal',
    display:  'swap',
    weight:   '400'
});

export const metadata = {
    title:       'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout(
    { children }: {
        children: React.ReactNode
    }) {
    return (
        <html lang="en">
        <body className={`${plusJakartaSans.variable} font-sans`}>
            {children}
        </body>
        </html>
    );
}
